Work branch
ClevertecFrontendLab/Lewiz1337 pull request #13
Opened 2023-03-06 17:48 UTC by Lewiz1337

2023-03-06 22:45 UTC, SergeyGlazun requested changes

2023-03-06 22:45 UTC, SergeyGlazun commented on package.json
>    "dependencies": {
![image](https://user-images.githubusercontent.com/70904466/223265607-8a547222-dd94-4d21-9d02-49fd3a8864f5.png)
если кликнули по полю и убрали курсов с поля то должно появиться сообщение что поле не должно быть пустым

2023-03-06 22:45 UTC, SergeyGlazun commented on src/components/authAlert/authAlertsContents/LoginAlertError.tsx
> +          dispatch(clearStatus());
лучше выносить выше в отдельный метод и передовать сюда потом const handleClick = () => {dispatch(clearStatus());...}

2023-03-06 22:45 UTC, SergeyGlazun commented on src/components/authAlert/authAlertsContents/LoginAlertError.tsx
> +          dispatch(clearStatus());
onClick={handleClick...

2023-03-06 23:04 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 20.
Количество непройденных тестов: 4.

2023-03-06 23:07 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 20.
Количество непройденных тестов: 4.

2023-03-07 15:36 UTC, Lewiz1337 commented
![image](https://user-images.githubusercontent.com/85436342/223470663-46d4e164-53be-4499-9fa8-08a44bd63e83.png)

2023-03-07 15:38 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 20.
Количество непройденных тестов: 0.
***
**error reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/error%20reset%20password.png)
***
**first enter.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/first%20enter.png)
***
**incorrect logit or password error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/incorrect%20logit%20or%20password%20error.png)
***
**loader authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/loader%20authorization.png)
***
**password hidden.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/password%20hidden.png)
***
**password shown.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/password%20shown.png)
***
**recovery page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/recovery%20page.png)
***
**registration already used error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/registration%20already%20used%20error.png)
***
**registration error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/registration%20error.png)
***
**registration page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/registration%20page.png)
***
**registration-first-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/registration-first-step.png)
***
**registration-second-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/registration-second-step.png)
***
**registration-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/registration-success.png)
***
**registration-third-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/registration-third-step.png)
***
**send email error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/send%20email%20error.png)
***
**send email success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/send%20email%20success.png)
***
**server error authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/server%20error%20authorization.png)
***
**success reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Lewiz1337/1678203495/success%20reset%20password.png)

2023-03-07 15:41 UTC, Lewiz1337 commented
Проблема решилась через запись ошибок в useState. Но, как про мне, это сильно испортило читаемость кода

2023-03-08 08:24 UTC, SergeyGlazun approved these changes

2023-03-08 13:19 UTC, merged